/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javierlopezproyectobd;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static javierlopezproyectobd.VentanaProyectoBD.hazConexion;

/**
 *
 * @author usuario
 */
public class Entrenador extends javax.swing.JDialog {

    private VentanaProyectoBD miPadre = null;
    DefaultTableModel dtmEntrenadores = null;

    /**
     * Creates new form Entrenador
     */
    public Entrenador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        miPadre = (VentanaProyectoBD) parent;
        int idEquipo = miPadre.getIdEquipo();
        visualizarEntrenador(idEquipo);
        btn_eliminarEntrenador.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_entrenador = new javax.swing.JTable();
        btn_addEntrenador = new javax.swing.JButton();
        btn_eliminarEntrenador = new javax.swing.JButton();
        btn_sync = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("ENTRENADORES:");

        tbl_entrenador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tbl_entrenador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_entrenadorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_entrenador);

        btn_addEntrenador.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_addEntrenador.setText("AÑADIR ENTRENADOR");
        btn_addEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addEntrenadorActionPerformed(evt);
            }
        });

        btn_eliminarEntrenador.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_eliminarEntrenador.setText("ELIMINAR ENTRENADOR");
        btn_eliminarEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarEntrenadorActionPerformed(evt);
            }
        });

        btn_sync.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javierlopezproyectobd/sync_blue.png"))); // NOI18N
        btn_sync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_syncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_sync)
                .addGap(77, 77, 77))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btn_eliminarEntrenador)
                        .addGap(44, 44, 44)
                        .addComponent(btn_addEntrenador)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sync))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_eliminarEntrenador)
                    .addComponent(btn_addEntrenador))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_entrenadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_entrenadorMouseClicked
        // TODO add your handling code here:
        btn_eliminarEntrenador.setEnabled(true);
    }//GEN-LAST:event_tbl_entrenadorMouseClicked

    private void btn_addEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addEntrenadorActionPerformed
        // TODO add your handling code here:
        AñadirEntrenador addEntrenador = new AñadirEntrenador(miPadre, true);
        addEntrenador.setVisible(true);
    }//GEN-LAST:event_btn_addEntrenadorActionPerformed

    private void btn_eliminarEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarEntrenadorActionPerformed
        // TODO add your handling code here:
        int idEquipo = miPadre.getIdEquipo();
        eliminarEntrenador(idEquipo);
        visualizarEntrenador(idEquipo);
        btn_eliminarEntrenador.setEnabled(false);
    }//GEN-LAST:event_btn_eliminarEntrenadorActionPerformed

    private void btn_syncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_syncActionPerformed
        // TODO add your handling code here:
        int idEquipo = miPadre.getIdEquipo();
        visualizarEntrenador(idEquipo);
        btn_eliminarEntrenador.setEnabled(false);
    }//GEN-LAST:event_btn_syncActionPerformed

    public void visualizarEntrenador(int idEquipo) {
        Statement s = null;
        ResultSet rs = null;
        Connection co = null;

        dtmEntrenadores = new DefaultTableModel();
        //dtmClasificaion.addColumn("Id");
        dtmEntrenadores.addColumn("Nombre");
        dtmEntrenadores.addColumn("País");

        //Asignamos el modelo a la vista tabla
        tbl_entrenador.setModel(dtmEntrenadores);
        co = miPadre.hazConexion();

        try {
            s = co.createStatement();
            rs = s.executeQuery("select nombre, pais from entrenador where idEquip=" + idEquipo);
            while (rs.next()) {
                Object[] fila = new Object[3];
                fila[0] = rs.getObject(1);
                fila[1] = rs.getObject(2);
                dtmEntrenadores.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaProyectoBD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void eliminarEntrenador(int idEquipo) {
        int res = 0;
        int i = tbl_entrenador.getSelectedRow();
        String nombre = (String) dtmEntrenadores.getValueAt(i, 0);
        PreparedStatement ps = null;
        Connection conex = hazConexion();

        try {
            ps = conex.prepareStatement("DELETE FROM entrenador WHERE nombre=? and idEquip=?");
            ps.setString(1, nombre);
            ps.setInt(2, idEquipo);

            res = ps.executeUpdate();
            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Entrenador eliminado correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "ERROR. No se eliminó ningun entrenador");
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaProyectoBD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrenador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Entrenador dialog = new Entrenador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addEntrenador;
    private javax.swing.JButton btn_eliminarEntrenador;
    private javax.swing.JButton btn_sync;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_entrenador;
    // End of variables declaration//GEN-END:variables
}
