/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javierlopezproyectobd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static javierlopezproyectobd.VentanaProyectoBD.PASSWORD;
import static javierlopezproyectobd.VentanaProyectoBD.URL;
import static javierlopezproyectobd.VentanaProyectoBD.USERNAME;
import static javierlopezproyectobd.VentanaProyectoBD.hazConexion;

/**
 *
 * @author usuario
 */
public class Jugadores extends javax.swing.JDialog {

    private VentanaProyectoBD miPadre = null;
    DefaultTableModel dtmJugadores = null;

    /**
     * Creates new form Jugadores
     *
     * @param parent
     * @param modal
     */
    public Jugadores(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        miPadre = (VentanaProyectoBD) parent;
        int idEquipo = miPadre.getIdEquipo();
        visualizarJugadores(idEquipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_portero = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_defensa = new javax.swing.JButton();
        btn_medio = new javax.swing.JButton();
        btn_delantero = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_jugadores = new javax.swing.JTable();
        btn_quitarFiltros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        btn_portero.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_portero.setText("Portero");
        btn_portero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_porteroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Posiciones:");

        btn_defensa.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_defensa.setText("Defensa");
        btn_defensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_defensaActionPerformed(evt);
            }
        });

        btn_medio.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_medio.setText("Centrocampista");
        btn_medio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_medioActionPerformed(evt);
            }
        });

        btn_delantero.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_delantero.setText("Delantero");
        btn_delantero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delanteroActionPerformed(evt);
            }
        });

        tbl_jugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tbl_jugadores);

        btn_quitarFiltros.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btn_quitarFiltros.setText("Quitar filtros");
        btn_quitarFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarFiltrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(538, 538, 538)
                .addComponent(btn_quitarFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(322, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_portero, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_defensa, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_medio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delantero, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(314, 314, 314))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(373, 373, 373))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(546, 546, 546))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_portero)
                    .addComponent(btn_defensa)
                    .addComponent(btn_medio)
                    .addComponent(btn_delantero))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_quitarFiltros)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_porteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_porteroActionPerformed
        // TODO add your handling code here:
        int idEquipo = miPadre.getIdEquipo();
        visualizarPortero(idEquipo);
    }//GEN-LAST:event_btn_porteroActionPerformed

    private void btn_defensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_defensaActionPerformed
        // TODO add your handling code here:
        int idEquipo = miPadre.getIdEquipo();
        visualizarDefensa(idEquipo);
    }//GEN-LAST:event_btn_defensaActionPerformed

    private void btn_medioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_medioActionPerformed
        // TODO add your handling code here:
        int idEquipo = miPadre.getIdEquipo();
        visualizarCentrocampista(idEquipo);
    }//GEN-LAST:event_btn_medioActionPerformed

    private void btn_delanteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delanteroActionPerformed
        // TODO add your handling code here:
        int idEquipo = miPadre.getIdEquipo();
        visualizarDelantero(idEquipo);
    }//GEN-LAST:event_btn_delanteroActionPerformed

    private void btn_quitarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarFiltrosActionPerformed
        // TODO add your handling code here:
        int idEquipo = miPadre.getIdEquipo();
        visualizarJugadores(idEquipo);
    }//GEN-LAST:event_btn_quitarFiltrosActionPerformed

    public void visualizarJugadores(int idEquipo) {
        Statement s = null;
        ResultSet rs = null;
        Connection co = null;

        dtmJugadores = new DefaultTableModel();
        //dtmClasificaion.addColumn("Id");
        dtmJugadores.addColumn("Nombre");
        dtmJugadores.addColumn("País");
        dtmJugadores.addColumn("Posición");

        //Asignamos el modelo a la vista tabla
        tbl_jugadores.setModel(dtmJugadores);
        co = miPadre.hazConexion();

        try {
            s = co.createStatement();
            rs = s.executeQuery("select nombre, pais, posicion from jugador where idEquip=" + idEquipo);
            while (rs.next()) {
                Object[] fila = new Object[3];
                fila[0] = rs.getObject(1);
                fila[1] = rs.getObject(2);
                fila[2] = rs.getObject(3);
                dtmJugadores.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaProyectoBD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void visualizarPortero(int idEquipo) {
        Statement s = null;
        ResultSet rs = null;
        Connection co = null;

        for (int i = 0; i < dtmJugadores.getRowCount(); i++) {
            dtmJugadores.removeRow(i);
        }

        dtmJugadores = new DefaultTableModel();
        //dtmClasificaion.addColumn("Id");
        dtmJugadores.addColumn("Nombre");
        dtmJugadores.addColumn("País");
        dtmJugadores.addColumn("Posición");

        //Asignamos el modelo a la vista tabla
        tbl_jugadores.setModel(dtmJugadores);
        co = miPadre.hazConexion();

        try {
            s = co.createStatement();
            rs = s.executeQuery("select nombre, pais, posicion from jugador where idEquip=" + idEquipo + " and posicion = 'Portero'");
            while (rs.next()) {
                Object[] fila = new Object[3];
                fila[0] = rs.getObject(1);
                fila[1] = rs.getObject(2);
                fila[2] = rs.getObject(3);
                dtmJugadores.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaProyectoBD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void visualizarDefensa(int idEquipo) {
        Statement s = null;
        ResultSet rs = null;
        Connection co = null;

        for (int i = 0; i < dtmJugadores.getRowCount(); i++) {
            dtmJugadores.removeRow(i);
        }

        dtmJugadores = new DefaultTableModel();
        //dtmClasificaion.addColumn("Id");
        dtmJugadores.addColumn("Nombre");
        dtmJugadores.addColumn("País");
        dtmJugadores.addColumn("Posición");

        //Asignamos el modelo a la vista tabla
        tbl_jugadores.setModel(dtmJugadores);
        co = miPadre.hazConexion();

        try {
            s = co.createStatement();
            rs = s.executeQuery("select nombre, pais, posicion from jugador where idEquip=" + idEquipo + " and posicion = 'Defensa'");
            while (rs.next()) {
                Object[] fila = new Object[3];
                fila[0] = rs.getObject(1);
                fila[1] = rs.getObject(2);
                fila[2] = rs.getObject(3);
                dtmJugadores.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaProyectoBD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void visualizarCentrocampista(int idEquipo) {
        Statement s = null;
        ResultSet rs = null;
        Connection co = null;

        for (int i = 0; i < dtmJugadores.getRowCount(); i++) {
            dtmJugadores.removeRow(i);
        }

        dtmJugadores = new DefaultTableModel();
        //dtmClasificaion.addColumn("Id");
        dtmJugadores.addColumn("Nombre");
        dtmJugadores.addColumn("País");
        dtmJugadores.addColumn("Posición");

        //Asignamos el modelo a la vista tabla
        tbl_jugadores.setModel(dtmJugadores);
        co = miPadre.hazConexion();

        try {
            s = co.createStatement();
            rs = s.executeQuery("select nombre, pais, posicion from jugador where idEquip=" + idEquipo + " and posicion = 'Centrocampista'");
            while (rs.next()) {
                Object[] fila = new Object[3];
                fila[0] = rs.getObject(1);
                fila[1] = rs.getObject(2);
                fila[2] = rs.getObject(3);
                dtmJugadores.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaProyectoBD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void visualizarDelantero(int idEquipo) {
        Statement s = null;
        ResultSet rs = null;
        Connection co = null;

        for (int i = 0; i < dtmJugadores.getRowCount(); i++) {
            dtmJugadores.removeRow(i);
        }

        dtmJugadores = new DefaultTableModel();
        //dtmClasificaion.addColumn("Id");
        dtmJugadores.addColumn("Nombre");
        dtmJugadores.addColumn("País");
        dtmJugadores.addColumn("Posición");

        //Asignamos el modelo a la vista tabla
        tbl_jugadores.setModel(dtmJugadores);
        co = miPadre.hazConexion();

        try {
            s = co.createStatement();
            rs = s.executeQuery("select nombre, pais, posicion from jugador where idEquip=" + idEquipo + " and posicion = 'Delantero'");
            while (rs.next()) {
                Object[] fila = new Object[3];
                fila[0] = rs.getObject(1);
                fila[1] = rs.getObject(2);
                fila[2] = rs.getObject(3);
                dtmJugadores.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaProyectoBD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Jugadores dialog = new Jugadores(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_defensa;
    private javax.swing.JButton btn_delantero;
    private javax.swing.JButton btn_medio;
    private javax.swing.JButton btn_portero;
    private javax.swing.JButton btn_quitarFiltros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_jugadores;
    // End of variables declaration//GEN-END:variables
}
